In [4]:
f = open('C:/Users/i/Desktop/2020빅콘테스트 문제데이터(혁신아이디어분야)/01_유동인구데이터(SK텔레콤)/4개지역_FLOW_AGE_201902.CSV','r',encoding='utf-8')
txt = f.read()
txt=txt.replace('|',',')
f.close()
txt
f = open('C:/Users/i/Desktop/test.csv','w',encoding='utf-8')
f.write(txt)
f.close()

In [5]:
import pandas as pd

txt_df =pd.read_csv('C:/Users/i/Desktop/test.csv',encoding='utf-8')

In [6]:
txt_df

,STD_YM,STD_YMD,HDONG_CD,HDONG_NM,MAN_FLOW_POP_CNT_0004,MAN_FLOW_POP_CNT_0509,MAN_FLOW_POP_CNT_1014,MAN_FLOW_POP_CNT_1519,MAN_FLOW_POP_CNT_2024,MAN_FLOW_POP_CNT_2529,...,WMAN_FLOW_POP_CNT_2529,WMAN_FLOW_POP_CNT_3034,WMAN_FLOW_POP_CNT_3539,WMAN_FLOW_POP_CNT_4044,WMAN_FLOW_POP_CNT_4549,WMAN_FLOW_POP_CNT_5054,WMAN_FLOW_POP_CNT_5559,WMAN_FLOW_POP_CNT_6064,WMAN_FLOW_POP_CNT_6569,WMAN_FLOW_POP_CNT_70U
0,201902,20190201,1114052000,소공동,16.64,116.18,419.70,1553.57,5196.07,11195.62,...,13323.19,12741.15,11628.80,10006.80,9807.06,8099.38,7260.17,5757.53,3359.85,4431.71
1,201902,20190202,1114052000,소공동,3.14,141.07,763.30,1405.29,4235.82,7592.34,...,7898.27,6580.27,5714.75,4946.22,5055.32,4560.27,4364.57,3838.77,2453.97,3207.26
2,201902,20190203,1114052000,소공동,1.38,120.39,698.23,1117.17,3032.90,5173.35,...,5079.63,4454.43,3905.32,3484.47,3703.24,3270.26,2984.05,2484.98,1511.67,1954.98
3,201902,20190204,1114052000,소공동,0.08,141.61,772.41,1248.85,3001.95,4641.82,...,4317.63,3676.47,3506.37,3108.99,3324.07,2841.35,2644.42,2164.35,1230.21,1520.35
4,201902,20190205,1114052000,소공동,0.00,254.70,1394.92,2190.69,3420.15,5478.30,...,4813.86,4967.92,5161.96,4856.63,5212.69,4462.94,4183.38,3265.62,1692.74,2147.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927,201902,20190224,2726069000,고산3동,0.05,146.86,677.67,1084.16,1545.11,1952.14,...,1502.39,1492.40,1980.33,2176.22,2912.72,2346.66,2167.17,1581.96,892.01,990.72
1928,201902,20190225,2726069000,고산3동,0.05,187.83,534.66,1024.18,1490.25,1840.75,...,1419.83,1502.75,2289.69,2481.96,3172.65,2942.42,2454.88,1797.78,1038.36,1206.05
1929,201902,20190226,2726069000,고산3동,0.03,146.97,494.97,925.04,1413.57,1748.78,...,1472.12,1493.60,2205.07,2522.17,3444.12,2866.35,2494.56,1863.79,1044.34,1225.85
1930,201902,20190227,2726069000,고산3동,0.08,164.30,555.82,1027.75,1437.50,1798.46,...,1436.20,1433.72,2195.25,2493.84,3286.59,2916.41,2450.63,1738.96,1014.68,1065.82
1931,201902,20190228,2726069000,고산3동,0.19,173.51,508.44,1107.87,1473.76,1977.00,...,1559.67,1510.90,2269.63,2624.71,3395.83,2945.19,2537.40,1924.45,1103.96,1259.71

In [8]:
f = open('C:/Users/i/Desktop/2020빅콘테스트 문제데이터(혁신아이디어분야)/03_SNS데이터(와이즈넛)/2020 bigcontest data_wisenut.csv','r',encoding='utf-8')
txt = f.read()
txt

UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 16: illegal multibyte sequence