# __Web crawl review__

In [ ]:
from selenium import webdriver
from bs4 import BeautifulSoup as BS
import time
import re
driver = webdriver.Chrome('c:/mychrome/chromedriver.exe')

def insta_search(kw):
    url = 'https://www.instagram.com/explore/tags/'+kw
    return url

def get_content(driver):
    html = driver.page_source
    soup = BS(html,'lxml')
    try:
        content = soup.select('div.C4VMK > span')[0].text
    except:
        content=' '
    tags = re.findall('#[^\s]+',content)

    date = soup.select('time._1o9PC.Nzb55')
    date = date[0]['datetime'][:10]
    likes_source = soup.select('button.sqdOP.yWX7d._8A5w5 > span')
    if likes_source:
        likes=likes_source[0].text
    else:
        likes=0
    place = soup.select('div.M30cS')[0].text
    ret = [content,date,likes,place,tags]
    return ret

driver.get('https://www.instagram.com')
time.sleep(2)

In [ ]:
import re
word='제주도맛집'
url = insta_search(word)
driver.get(url)
time.sleep(3)
first = driver.find_element_by_css_selector('div._9AhH0')
first.click()
time.sleep(3)

get_content(driver)

In [ ]:
def moveNext(driver):
    right = driver.find_element_by_css_selector('a._65Bje.coreSpriteRightPaginationArrow')
    right.click()
    time.sleep(2)

moveNext(driver)

In [ ]:
# 오후 연습 문제
# 50개 게시글을 스크랩 하여 DF 로 저장
results=[]

data=get_content(driver)
result.append(data)
moveNext(driver)

# __Pandas , Numpy__

In [ ]:
import pandas as pd
import numpy as np

arr = np.arange(12) # 같은 생김새지만 배열이라는 차이점
print(arr,arr.shape)
arr2=arr.reshape(3,4)
print(arr2,arr2.shape)
print(arr,arr.shape)   # reshape 은 복사본 리턴

In [ ]:
df1=pd.DataFrame(data=arr2,columns=['c1','c2','c3','c4'],index=['r1','r2','r3'])
df1

In [ ]:
df2=pd.DataFrame(data=[[1,2,4],[3,5,6]],columns=['c1','c2','c3'],index=['r1','r2'])
df2

# __스타벅스 크롤링__  
* 가설 : 인구수가 많은 위치에 매장도 몰려있지 않을까?  
* 스타벅스 홈페이지 -> 매장 정보 -> 크롤링  
* 서울시 열린데이터 광장 -> 인구통계 데이터 
* open API : 데이터분석에 있어 데이터를 제공할 수 있도록 만든 인터페이스

In [ ]:
import selenium.webdriver as sw
from bs4 import BeautifulSoup as bs
import time
import pandas as pd

# 스타벅스 매장 찾기 브라우저 제어
driver = sw.Chrome('c:/mychrome/chromedriver.exe')
url='https://www.starbucks.co.kr/store/store_map.do?disp=locale'
driver.get(url)
time.sleep(2)

In [ ]:
# 서울 카테고리 클릭
seoul_btn = 'ul.sido_arae_box > li:nth-child(1) > a'
seoul_cat=driver.find_element_by_css_selector(seoul_btn)
seoul_cat.click()
time.sleep(2)

In [ ]:
# 전체 버튼 클릭
all_btn = '#mCSB_2_container > ul > li:nth-child(1) > a'
all_cat = driver.find_element_by_css_selector(all_btn)
all_cat.click()
time.sleep(2)

In [ ]:
# 페이지 html get
html = driver.page_source
soup = bs(html,'html.parser')

In [ ]:
# 한 매장의 위치 지표 및 상호 select
starbucks_L = soup.select('li.quickResultLstCon')
starbucks_store=starbucks_L[0]
lat=starbucks_store['data-lat'].strip()
lng=starbucks_store['data-long'].strip()
name = starbucks_store.select('strong')[0].text.strip()
print(name,lat,lng)

In [ ]:
# 매장 타입
starbucks_store.select('i')[0]

In [ ]:
str(starbucks_store.select('p.result_details')[0])

# __서울 공공데이터 활용 실습__  
* 개인 key : 536468687a6c656536385561645750

In [ ]:
my_key='536468687a6c656536385561645750'
url = f'http://openapi.seoul.go.kr:8088/{my_key}/json/SdeTlSccoSigW/1/25/'

In [ ]:
import requests
data = requests.get(url).json()
for info in data['SdeTlSccoSigW']['row']:
    for k,i in info.items():
        print(k,i)
    print('='*15)
print(data['SdeTlSccoSigW']['RESULT'])

In [ ]:
import pandas as pd

sampleDF = pd.DataFrame(data['SdeTlSccoSigW']['row'])
sampleDF

### __일반화 함수를 이용하여 시군구 open api 호출__

In [24]:
import requests
import pandas as pd

my_key='536468687a6c656536385561645750'

def SOA_get_data(url,service): # SOA : Seoul Open Api
    data_list = None
    try:
        result_dict = requests.get(url).json()
        result_data = result_dict[service]
        if result_data['RESULT']['CODE']=='INFO-000':
            data_list = result_data['row']
    except KeyError:
        pass
    return data_list

def SOA_make_url(key,s_idx,e_idx,service):
    return f'http://openapi.seoul.go.kr:8088/{key}/json/{service}/{s_idx}/{e_idx}/'

sgg_data = SOA_get_data(SOA_make_url(my_key,1,25,'SdeTlSccoSigW'),'SdeTlSccoSigW')
if not sgg_data:
    print('잘못된 서비스명으로 접근')
else:
    sgg_df = pd.DataFrame(data=sgg_data,columns=['SIG_CD','SIG_KOR_NM','LAT','LNG'])

In [27]:
sgg_df.columns=['시군구 코드','시군구 한글명','위도','경도']
sgg_df

   시군구 코드 시군구 한글명          위도           경도
0   11320     도봉구  37.6658609  127.0317674
1   11380     은평구  37.6176125  126.9227004
2   11230    동대문구  37.5838012  127.0507003
3   11590     동작구  37.4965037  126.9443073
4   11545     금천구  37.4600969  126.9001546
5   11530     구로구  37.4954856   126.858121
6   11110     종로구  37.5990998  126.9861493
7   11305     강북구  37.6469954  127.0147158
8   11260     중랑구  37.5953795  127.0939669
9   11680     강남구  37.4959854  127.0664091
10  11500     강서구  37.5657617  126.8226561
11  11140      중구  37.5579452  126.9941904
12  11740     강동구  37.5492077  127.1464824
13  11215     광진구  37.5481445  127.0857528
14  11440     마포구  37.5622906  126.9087803
15  11650     서초구  37.4769528  127.0378103
16  11290     성북구   37.606991  127.0232185
17  11350     노원구   37.655264  127.0771201
18  11710     송파구  37.5048534  127.1144822
19  11410    서대문구  37.5820369  126.9356665
20  11470     양천구  37.5270616  126.8561534
21  11560    영등포구   37.520641  126.9139242
22  11620     관악구  37.4653993  126.9438071
23  11200     성동구  37.5506753  127.0409622
24  11170     용산구  37.5311008  126.9810742

* 오픈 api 로부터 받아온 데이터로 만든 DataFrame 을 Excel 파일로 저장해보기

In [28]:
sgg_df.to_excel('seoul_sgg_list.xlsx',index=False)

* 구별 서울 인구수 가져와보기 = 서비스 명만 변경

In [30]:
service_name='octastatapi419'
pop_data = SOA_get_data(SOA_make_url(my_key,1,26,service_name),service_name)
if not pop_data:
    print('잘못된 서비스명으로 접근')
else:
    pop_df = pd.DataFrame(data=pop_data)

In [40]:
condition = pop_df['JACHIGU']!='합계'  # boolean reference
pop_df_selected = pop_df[condition]
pop_df_important = pop_df_selected[['JACHIGU','GYE_1']]
pop_df_important.columns=['시군구명','주민등록인구']
pop_df_important.to_excel('pop_df.xlsx',index=False)

* 서울시 동별 사업체 현황 api 호출

In [41]:
service_name='octastatapi104'          # 8088 포트번호 : 물리적으로는 하나의 ip주소로 접근 , 논리적으로는 6만 포트중 하나
busy_data = SOA_get_data(SOA_make_url(my_key,1,450,service_name),service_name)
if not busy_data:
    print('잘못된 서비스명으로 접근')
else:
    busy_df = pd.DataFrame(data=busy_data)

In [44]:
condition = busy_df['DONG']=='소계'
print('구 단위 사업체 현황')
busy_df_selected = busy_df[condition]
busy_df_selected

구 단위 사업체 현황

,GIGAN,JACHIGU,DONG,SAEOPCHESU_1,YEOSEONGDAEPYOJA,GYE,NAM,YEO,SAEOPCHESU_2,JONGSAJASU_1,...,JONGSAJASU_4,SAEOPCHESU_6,JONGSAJASU_5,SAEOPCHESU_7,JONGSAJASU_6,SAEOPCHESU_8,JONGSAJASU_7,SAEOPCHESU_9,JONGSAJASU_8,SAEOPCHESU_10
1,2015,종로구,소계,40871,13472,269106,152766,116340,1,16,...,387,9,179,358,25269,17447,46970,1418,7841,6635
19,2015,중구,소계,66190,24249,423808,234337,189471,-,-,...,1048,8,159,451,7364,34785,100132,1666,16214,6142
35,2015,용산구,소계,21178,7030,133446,76287,57159,-,-,...,55,12,167,440,7483,7714,30638,1292,4458,4245
52,2015,성동구,소계,26130,7617,162019,97243,64776,-,-,...,816,31,439,661,6049,7090,31229,2641,7832,3494
70,2015,광진구,소계,24531,8627,123689,69279,54410,-,-,...,93,16,145,836,10047,6214,20209,2511,7399,4555
86,2015,동대문구,소계,32994,10813,143858,77571,66287,-,-,...,1,17,134,777,6390,11740,33122,3600,7362,5101
101,2015,중랑구,소계,27287,8952,99241,51968,47273,-,-,...,105,19,208,906,5146,5540,16872,6225,12937,4010
118,2015,성북구,소계,24690,8883,113893,57411,56482,-,-,...,6,16,184,594,3894,5453,16944,3601,6921,4411
139,2015,강북구,소계,18654,6738,69787,33584,36203,-,-,...,206,8,149,481,2018,3976,10676,3131,6539,3667
153,2015,도봉구,소계,18455,6142,68669,36066,32603,1,1,...,-,12,119,493,2832,3667,11499,4786,9675,2675
168,2015,노원구,소계,25827,9000,114736,55090,59646,1,2,...,219,14,146,494,2302,5105,15649,6338,11822,4111
188,2015,은평구,소계,24179,9029,87693,42879,44814,-,-,...,150,14,189,656,5044,5154,15272,5041,8740,4016
205,2015,서대문구,소계,19612,7253,111615,56198,55417,-,-,...,523,10,169,483,3753,4214,14644,2928,5786,4280
220,2015,마포구,소계,36504,11901,252534,141953,110581,-,-,...,437,27,346,1152,14703,8049,34481,3072,14219,7511
237,2015,양천구,소계,26297,9423,119443,63854,55589,-,-,...,465,23,329,831,9629,5744,18149,5054,12432,3596
256,2015,강서구,소계,33273,11281,199289,109448,89841,1,28,...,500,44,655,1043,11570,8094,31565,6856,49775,4901
277,2015,구로구,소계,37445,10600,210506,123080,87426,1,1,...,79,22,211,1043,10750,11920,38676,4699,9578,4544
293,2015,금천구,소계,30080,8000,223058,142086,80972,-,-,...,11,25,208,1067,12634,8342,37322,2771,9067,3294
304,2015,영등포구,소계,44512,13068,362524,215032,147492,-,-,...,704,19,388,1381,17996,12192,56809,4172,14159,6946
323,2015,동작구,소계,19609,7593,103915,53424,50491,-,-,...,421,14,206,575,4726,4882,15286,2109,3126,3938
339,2015,관악구,소계,26235,9672,119180,61798,57382,-,-,...,-,15,194,728,9779,5500,16432,3949,6224,5490
361,2015,서초구,소계,47061,14659,439963,269984,169979,-,-,...,320,16,218,2037,68590,12668,70200,1406,10773,6743
380,2015,강남구,소계,73590,22847,711278,405780,305498,4,79,...,1778,25,810,2249,55801,17848,145803,3143,12261,11201
403,2015,송파구,소계,45375,15109,302517,181835,120682,5,329,...,51,31,492,1894,38462,13874,57745,5632,14682,6543
431,2015,강동구,소계,30079,10609,143061,78766,64295,3,35,...,338,16,268,1065,17961,7282,26082,5601,10099,4736

In [51]:
busy_df_final = busy_df_selected[['JACHIGU','GYE','SAEOPCHESU_1']]
busy_df_final.columns=['시군구 명','계','사업체 수']
busy_df_final = busy_df_final.reset_index(drop=True)
busy_df_final.to_excel('busy_df.xlsx',index=False)

# __Pandas read excel__

In [70]:
import pandas as pd 
seoul_starbucks = pd.read_excel('seoul_starbucks_list.xlsx')
seoul_starbucks.head()

,매장명,위도,경도,매장타입,주소,전화번호
0,역삼아레나빌딩,37.501087,127.043069,general,서울특별시 강남구 언주로 425 (역삼동),1522-3232
1,논현역사거리,37.510178,127.022223,general,서울특별시 강남구 강남대로 538 (논현동),1522-3232
2,신사역성일빌딩,37.514132,127.020563,general,서울특별시 강남구 강남대로 584 (논현동),1522-3232
3,국기원사거리,37.499517,127.031495,general,서울특별시 강남구 테헤란로 125 (역삼동),1522-3232
4,스탈릿대치R,37.494668,127.062583,reserve,서울특별시 강남구 남부순환로 2947 (대치동),1522-3232

In [75]:
sgg_names=[]
for addr in seoul_starbucks['주소']:
    sgg_names.append(addr.split()[1])

#칼럼 추가
seoul_starbucks['시군구 명']=sgg_names
seoul_starbucks.head()

seoul_starbucks.to_excel('seoul_starbucks_list.xlsx',index=False)

### * 시군군 데이터 병합

In [106]:
seoul_sgg = pd.read_excel('seoul_sgg_list.xlsx')
#	시군구 코드	시군구 한글명	위도	경도

seoul_starbucks = pd.read_excel('seoul_starbucks_list.xlsx')
#매장명	위도	경도	매장타입	주소	전화번호

# 피봇(pivot) 함수 : 피봇팅 (특정 기준에 따른 데이터 요약)
seoul_sgg.columns=['시군구 코드','시군구 명','위도','경도']

In [108]:
# 구 별로 스타벅스 매장 개수 세기
seoul_starbucks_sgg_count = seoul_starbucks.pivot_table(index = '시군구 명',values='매장명',aggfunc='count').rename(columns={'매장명':'스타벅스 매장 수'})
seoul_starbucks_sgg_count=seoul_starbucks_sgg_count.drop(['67'])

In [114]:
# 시군구 정보와 합치기
tmp = pd.merge(seoul_sgg,seoul_starbucks_sgg_count,how='left',on='시군구 명')

In [115]:
seoul_sgg_pop = pd.read_excel('pop_df.xlsx')
seoul_sgg_pop.columns = ['시군구 명','주민등록인구']
tmp2 = pd.merge(tmp,seoul_sgg_pop,how='left',on='시군구 명')

    시군구 코드 시군구 명         위도          경도  스타벅스 매장 수   주민등록인구
0    11320   도봉구  37.665861  127.031767          2  371,095
1    11380   은평구  37.617612  126.922700          8  474,165
2    11230  동대문구  37.583801  127.050700          8  374,039
3    11590   동작구  37.496504  126.944307         11  407,966
4    11545   금천구  37.460097  126.900155         10  262,337
5    11530   구로구  37.495486  126.858121         10  449,187
6    11110   종로구  37.599100  126.986149         38  177,023
7    11305   강북구  37.646995  127.014716          5  342,669
8    11260   중랑구  37.595379  127.093967          7  431,283
9    11680   강남구  37.495985  127.066409         80  570,913
10   11500   강서구  37.565762  126.822656         16  578,257
11   11140    중구  37.557945  126.994190         52  138,102
12   11740   강동구  37.549208  127.146482         15  490,945
13   11215   광진구  37.548144  127.085753         15  386,292
14   11440   마포구  37.562291  126.908780         32  392,087
15   11650   서초구  37.476953  127.037810         46  432,888
16   11290   성북구  37.606991  127.023218         13  484,359
17   11350   노원구  37.655264  127.077120         13  614,603
18   11710   송파구  37.504853  127.114482         31  689,909
19   11410  서대문구  37.582037  126.935667         19  336,490
20   11470   양천구  37.527062  126.856153         15  504,928
21   11560  영등포구  37.520641  126.913924         34  440,863
22   11620   관악구  37.465399  126.943807         11  546,814
23   11200   성동구  37.550675  127.040962         11  316,113
24   11170   용산구  37.531101  126.981074         19  250,844

In [121]:
seoul_sgg_busy = pd.read_excel('busy_df.xlsx')
seoul_sgg_busy.columns = ['시군구 명','종사자 수','사업체 수']
seoul_sgg_total = pd.merge(tmp2,seoul_sgg_busy,how='left',on='시군구 명')
seoul_sgg_total

    시군구 코드 시군구 명         위도          경도  스타벅스 매장 수   주민등록인구   종사자 수  사업체 수
0    11320   도봉구  37.665861  127.031767          2  371,095   68669  18455
1    11380   은평구  37.617612  126.922700          8  474,165   87693  24179
2    11230  동대문구  37.583801  127.050700          8  374,039  143858  32994
3    11590   동작구  37.496504  126.944307         11  407,966  103915  19609
4    11545   금천구  37.460097  126.900155         10  262,337  223058  30080
5    11530   구로구  37.495486  126.858121         10  449,187  210506  37445
6    11110   종로구  37.599100  126.986149         38  177,023  269106  40871
7    11305   강북구  37.646995  127.014716          5  342,669   69787  18654
8    11260   중랑구  37.595379  127.093967          7  431,283   99241  27287
9    11680   강남구  37.495985  127.066409         80  570,913  711278  73590
10   11500   강서구  37.565762  126.822656         16  578,257  199289  33273
11   11140    중구  37.557945  126.994190         52  138,102  423808  66190
12   11740   강동구  37.549208  127.146482         15  490,945  143061  30079
13   11215   광진구  37.548144  127.085753         15  386,292  123689  24531
14   11440   마포구  37.562291  126.908780         32  392,087  252534  36504
15   11650   서초구  37.476953  127.037810         46  432,888  439963  47061
16   11290   성북구  37.606991  127.023218         13  484,359  113893  24690
17   11350   노원구  37.655264  127.077120         13  614,603  114736  25827
18   11710   송파구  37.504853  127.114482         31  689,909  302517  45375
19   11410  서대문구  37.582037  126.935667         19  336,490  111615  19612
20   11470   양천구  37.527062  126.856153         15  504,928  119443  26297
21   11560  영등포구  37.520641  126.913924         34  440,863  362524  44512
22   11620   관악구  37.465399  126.943807         11  546,814  119180  26235
23   11200   성동구  37.550675  127.040962         11  316,113  162019  26130
24   11170   용산구  37.531101  126.981074         19  250,844  133446  21178

In [122]:
seoul_sgg_total.to_excel('seoul_sgg_total.xlsx')